package fuentes;

public enum EspecialidadMedica {
	GENERAL, CARDIOVASCULAR, OTORRINO, RESPIRATORIO, DIGESTIVO, TRAUMA, INTERNA, DERMATOLOGIA, PEDIATRIA, GINECOLOGIA, ODONTOLOGIA, CARDIOLOGIA, NEUROLOGIA;
}
